### ISSUE TITLE
Recruitable NPC?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-CustomKits#1]
Hey there Argent,

The mod here introduces the spellsword kit. My main character is usually a human that first
picks berserker class, then becomes a mage, simply because I love the magic system, and 
berserker ability makes the game more convenient (resistance to mind flayers in a vanilla
run for instance). So I will rarely test the spellsword kit because my main character is already
pre-set to that dual class.

But, perhaps there could be a NPC added? It does not need any fancy background, though
perhaps explaining where that NPC came from may be nice. It should be a recruitable
NPC that uses the spellsword kit. To make addition simple, that NPC does not need 
any special item or quest - it should just have some name and be a spellsword and be
recruitable. That way players who want to test the spellsword, can do so, through that
joinable NPC.

Anyway, that was my suggestion - please feel free to handle this issue request in any
way you see fit, including closing it at any moment in time.

**Comment by Argent77** [comment]
Thanks for the suggestion, but I consider this mod as complete and won't therefore add or expand any more features. Translations or other contributions to the mod are still welcome though.

Btw, you can use the "Create Party" option of the game to create more than one character during character creation, or create your own recruitable NPCs with the [NPC Generator](https://github.com/Argent77/A7-NPCGenerator).
